title: intUItive!
description: intUItive! is a VR application to showcase UI/UX design principles.
logo: /assets/img/logo.png
author: CS4240-05

header_navigation:
  - title: UI Distance
    url: /1_UIDistance/relocation.md

  - title: Grabbing
    url: 2_Grabbing/grabbing.md

  - title: HUD
    url: 3_HUD/hud.md

  - title: UI Height
    url: 4_UIHeight/height.md

  - title: UI Resize
    url: 5_UIResize/resize.md

  - title: Hick's Law
    url: 6_Hickslaw/hickslaw.md

footer_navigation:
  - title: repo
    url: "https://github.com/cs4240-group5/intuitive"

  - title: Vote for us!
    url: "https://uvents.nus.edu.sg/event/22nd-steps/vote"
#
#header_pages:
#  - "1_UIDistance/relocation.md"
#  - "2_Grabbing/grabbing.md"
#  - "3_HUD/hud.md"
#  - "4_UIHeight/height.md"
#  - "5_UIResize/resize.md"
#  - "6_HicksLaw/hickslaw.md"

markdown: kramdown


show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
