title: intUItive!
description: intUItive! is a VR application to showcase UI/UX design principles.
logo: /assets/img/logo.png
author: CS4240-05

site_navigation:
  - title: UI Distance
    url: /docs/1_UIDistance/relocation.md

  - title: Grabbing
    url: /docs/2_Grabbing/grabbing.md

  - title: HUD
    url: /docs/3_HUD/hud.md

  - title: UI Height
    url: /docs/4_UIHeight/height.md

  - title: UI Resize
    url: /docs/5_UIResize/resize.md

  - title: Hick's Law
    url: /docs/6_Hickslaw/hickslaw.md

footer_navigation:
  - title: repo
    url: "https://github.com/cs4240-group5/intuitive"

  - title: Vote for us!
    url: "https://uvents.nus.edu.sg/event/22nd-steps/vote"



markdown: kramdown


show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
