theme: minima
title: "intUItive!"

author: 
  name: "CS4240-05"

header_pages:
  - "1_UIDistance/relocation.md"
  - "2_Grabbing/grabbing.md"
  - "3_HUD/hud.md"
  - "4_UIHeight/height.md"
  - "5_UIResize/resize.md"
  - "6_HicksLaw/hickslaw.md"

about_us: aboutus.md

plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
  - jemoji

markdown: kramdown

repository: "cs4240-group5/intuitive"
github_icon: "Logos/PNG/Logo_Square.png"